split user facing script command generation and execution
If importing scripts, do:

    import gufi_config
    import <gufi_tool>

    config = gufi_config.Server(gufi_config.PATH)
    args = <gufi_tool>.parse_args(argv) # flags should start at argv[1]
    if <gufi_tool> == gufi_find:
        args.paths = [paths]
    cmds = <gufi_tool>.gen_cmds(config, args)

cmds will contain a list of commands (list of strings) to run:

    cmds = [
        ['gufi_query', ...],
        ['gufi_query', ...],
        ...
    ]

Exception: gufi_du.gen_cmds returns cmds=[[cmd, path], ...] instead
of cmds=[cmd, ...]

There may be fewer commands than inputted paths because while
gufi_query must process file paths one at a time, directory paths may
sometimes be all passed to the same command.

Ways to use these commands:
    - pass them to subprocess.Popen
    - extract flags + flag arguments and construct a gufi_vt command