gufi_dir2index: nda.topath used unitialized in error case
Trevor reported that gufi_dir2index was seg faulting when running in
production. We ran it under ASAN and saw the following double-free was
reported:

```
$ ./gufi_dir2index --threads 64 /users /output
"/output" Already exists!
Creating GUFI tree /output with 64 threads
Error: Could not open directory "/users/some/long/path/": No such file or directory (2)
=================================================================
==3028882==ERROR: AddressSanitizer: attempting double-free on 0x7c922f276880 in thread T26:
    #0 0x0000004d0d3a in free (/opt/hpcinf/gufi-builds/GUFI-d3f09192/build-debug/src/gufi_dir2index+0x4d0d3a) (BuildId: 2bd9fc7a06341e3e8ed7d07a556d0735c9b9ea01)
    #1 0x0000005172cb in processdir /opt/hpcinf/gufi-builds/GUFI-d3f09192/src/gufi_dir2index.c:365:5
    #2 0x00000051c83d in process_work /opt/hpcinf/gufi-builds/GUFI-d3f09192/src/QueuePerThreadPool.c:313:36
    #3 0x000000519e63 in worker_function /opt/hpcinf/gufi-builds/GUFI-d3f09192/src/QueuePerThreadPool.c:356:35
    #4 0x0000004cea3c in asan_thread_start(void*) asan_interceptors.cpp.o
    #5 0x7fd23015b1c9 in start_thread (/lib64/libpthread.so.0+0x81c9) (BuildId: 601e076f2ed363fb96f707b98d1144cdd94878b8)
    #6 0x7fd22f77e952 in clone (/lib64/libc.so.6+0x39952) (BuildId: 1faac7cdefc71ce73027e33a84650684eecd1635)

0x7c922f276880 is located 0 bytes inside of 120-byte region [0x7c922f276880,0x7c922f2768f8)
freed by thread T28 here:
    #0 0x0000004d0d3a in free (/opt/hpcinf/gufi-builds/GUFI-d3f09192/build-debug/src/gufi_dir2index+0x4d0d3a) (BuildId: 2bd9fc7a06341e3e8ed7d07a556d0735c9b9ea01)
    #1 0x000000599a94 in clearSelect sqlite3.c

previously allocated by thread T28 here:
    #0 0x0000004d0fd8 in malloc (/opt/hpcinf/gufi-builds/GUFI-d3f09192/build-debug/src/gufi_dir2index+0x4d0fd8) (BuildId: 2bd9fc7a06341e3e8ed7d07a556d0735c9b9ea01)
    #1 0x000000577433 in sqlite3MemMalloc sqlite3.c

Thread T26 created by T0 here:
    #0 0x0000004b5595 in pthread_create (/opt/hpcinf/gufi-builds/GUFI-d3f09192/build-debug/src/gufi_dir2index+0x4b5595) (BuildId: 2bd9fc7a06341e3e8ed7d07a556d0735c9b9ea01)
    #1 0x000000519b96 in QPTPool_start /opt/hpcinf/gufi-builds/GUFI-d3f09192/src/QueuePerThreadPool.c:698:21
    #2 0x000000513da6 in main /opt/hpcinf/gufi-builds/GUFI-d3f09192/src/gufi_dir2index.c:593:9
    #3 0x7fd22f77f864 in __libc_start_main (/lib64/libc.so.6+0x3a864) (BuildId: 1faac7cdefc71ce73027e33a84650684eecd1635)

Thread T28 created by T0 here:
    #0 0x0000004b5595 in pthread_create (/opt/hpcinf/gufi-builds/GUFI-d3f09192/build-debug/src/gufi_dir2index+0x4b5595) (BuildId: 2bd9fc7a06341e3e8ed7d07a556d0735c9b9ea01)
    #1 0x000000519b96 in QPTPool_start /opt/hpcinf/gufi-builds/GUFI-d3f09192/src/QueuePerThreadPool.c:698:21
    #2 0x000000513da6 in main /opt/hpcinf/gufi-builds/GUFI-d3f09192/src/gufi_dir2index.c:593:9
    #3 0x7fd22f77f864 in __libc_start_main (/lib64/libc.so.6+0x3a864) (BuildId: 1faac7cdefc71ce73027e33a84650684eecd1635)

SUMMARY: AddressSanitizer: double-free (/opt/hpcinf/gufi-builds/GUFI-d3f09192/build-debug/src/gufi_dir2index+0x4d0d3a) (BuildId: 2bd9fc7a06341e3e8ed7d07a556d0735c9b9ea01) in free
==3028882==ABORTING
```

This is kind of confusing because it's not clear why nda.topath.data,
freed at the end of processdir() (gufi_dir2index.c:365 at commit
d3f09192), would have been originally allocated
by sqlite3MemMalloc().

However, the error message about the directory not existing gives a
clue.

It looks like when that error is hit at the beginning of processdir(),
control jumps to the cleanup label before nda.topath is initialized.
Thus, free(nda.topath.data) is given a garbage value to free. It looks
like by chance that ended up being a previously freed sqlite object.

The solution is to initialize nda.topath at the beginning of
processdir().

Reported-by: Trevor Bautista <tbautista@lanl.gov>
Fixes: a2cb2d7a8518 ("add generic data member to PluginCommonStruct")